#!/bin/bash

psql << EOF

CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';

CREATE DATABASE $DATABASE_NAME
    WITH
    OWNER = $DATABASE_USERNAME
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

EOF