SERVER_STARTED = "Servidor iniciado"
SERVER_STOPPED = "Servidor detenido"

USER_LOGIN = "SOLICITUD DE INICIO DE SESIÓN POR EL USUARIO {user_id}"
USER_TOKEN_RENEW = "SOLICITUD DE RENOVACIÓN DE TOKEN POR EL USUARIO {user_id}"

RESOURCE_REQUEST = "{http_method} EN {resource_url} SOLICITADO POR EL USUARIO {user_id}"
