version: "3.9"
services:
  postgres:
    container_name: ${DATABASE_IP}
    image: postgres:15.5
    expose:
      - "${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker_files/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    restart: on-failure:${CONTAINER_RETRIES}
    env_file:
      - .env

  server:
    build: 
      context: .
      dockerfile: docker_files/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DEVELOPMENT=False
    links:
      - ${DATABASE_IP}
    depends_on:
      - ${DATABASE_IP}
    volumes:
      - app_logs:/${LOGS_PATH}
    restart: on-failure:${CONTAINER_RETRIES}
    env_file:
      - .env

volumes:
  postgres_data:
  app_logs: